version: '2.0'
services:
  web:
    build: .
    environment:
      HTTPS_PORT: '10443'
      HTTP_PORT: '10080'
    depends_on:
    - db
    network_mode: bridge
    ports:
    - 10080:80
    - 10443:443
    volumes:
    - ./html:/var/www/html:rw
  db:
    environment:
      MYSQL_DATABASE: lamp_db
      MYSQL_PASSWORD: lamp_P
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lamp_L
    image: mariadb:10.2
    network_mode: bridge
    ports:
    - 13306:3306
    volumes:
    - ./mysql:/var/lib/mysql:rw
  

  
