networks: {}
services:
  db:
    environment:
      MYSQL_DATABASE: lamp_db
      MYSQL_PASSWORD: lamp_P
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lamp_L
    image: mariadb:10.2
    network_mode: bridge
    ports:
    - 13306:3306/tcp
    volumes:
    - ./mysql:/var/lib/mysql:rw
  web:
    build:
      context: ./php
      dockerfile: Dockerfile-php71
    environment:
      HTTPS_PORT: '10443'
      HTTP_PORT: '10080'
    links:
    - db
    network_mode: bridge
    ports:
    - 10080:80/tcp
    - 10443:443/tcp
    volumes:
    - ./html:/var/www/html:rw
version: '2.1'
volumes: {}
